<?php

declare(strict_types=1);

namespace Pagekit\Routing\Generator;

use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\RouteCollection;

/**
 * Generates URLs from dumped route data instead of a route collection.
 *
 * Symfony's own compiled generator cannot stand in for this one: it keeps its
 * route data private and only resolves names, while Pagekit generates from the
 * same six values through getRouteProperties() - the lookup Router::generate()
 * uses to hand a route's defaults to a params resolver before generating, and
 * the one doGenerate() uses again for the LINK_URL reference type. Extending
 * the collection-backed generator keeps that behaviour and replaces only where
 * the six values come from.
 */
class CompiledUrlGenerator extends UrlGenerator
{
    /**
     * @var array<string, array<int, mixed>>
     */
    private array $compiledRoutes;

    /**
     * @param array<string, array<int, mixed>> $compiledRoutes Route data as written by dump(), keyed by route name
     */
    public function __construct(array $compiledRoutes, RequestContext $context)
    {
        // An empty collection is enough: every lookup this class answers reads
        // the dumped data, and the parent only touches the collection in the
        // generate() implementation replaced below.
        parent::__construct(new RouteCollection(), $context);

        $this->compiledRoutes = $compiledRoutes;
    }

    /**
     * Dumps a route collection as the data file this class reads back.
     *
     * The file is data, not a class: it carries the values compiling a route
     * yields - the work the cache exists to skip - and nothing that could run.
     * A tampered or half-written file therefore stays inert until the reader
     * validates it, instead of being executed to find out.
     */
    public static function dump(RouteCollection $routes): string
    {
        $compiled = [];

        foreach ($routes->all() as $name => $route) {
            $compiledRoute = $route->compile();

            $compiled[$name] = [
                $compiledRoute->getVariables(),
                $route->getDefaults(),
                $route->getRequirements(),
                $compiledRoute->getTokens(),
                $compiledRoute->getHostTokens(),
                $route->getSchemes(),
            ];
        }

        return sprintf("<?php\n\n// Route data generated by Pagekit. Do not edit.\n\nreturn %s;\n", var_export($compiled, true));
    }

    /**
     * {@inheritdoc}
     *
     * @param array<string, mixed> $parameters
     */
    public function generate(string $name, array $parameters = [], int $referenceType = self::ABSOLUTE_PATH): string
    {
        if (!isset($this->compiledRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }

        [$variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes] = $this->compiledRoutes[$name];

        return $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, $requiredSchemes);
    }

    /**
     * {@inheritdoc}
     *
     * @return array<int, mixed>|null
     */
    public function getRouteProperties(string $name): ?array
    {
        return $this->compiledRoutes[$name] ?? null;
    }
}
